<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 1: Python Coding Exercises

_Authors: Joseph Nelson (DC)_

---

The following code challenges are drawn from common exercises used in technical interviews.

Please note that there may be several ways to approach each challenge. If you get stuck, try mapping out your approach in pseudocode first. Finally, while solutions to problems like these may be found online, remember that if you copy/paste code that you can't explain, you'll be missing out on the point of the project. The only way to truly learn a new skill is through practice, trial, and error - we can only help you improve by understanding where you are having trouble.

In [1]:
import numpy as np
import pandas as pd
import math

## Challenge 1: Largest Palindrome
A palindromic number reads the same both ways. For example, 1234321 is a palindrome. The largest palindrome made from the product of two two-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two three-digit numbers. Afterward, write a brief explanation walking through your code's logic in markdown.

### Prework
I want to run a loop that considers every combination of 3-digit number. First, check how many combinations that creates to decide if this is a terrible idea or not

In [2]:
nums = np.arange(100,1000)
len(nums)

900

In [3]:
# how many combinations of r=2 items from n=900?
# C(n,r) = n! / (n-r)! * r!

def count_combinations(n,r):
    combinations = math.factorial(n) / (math.factorial(n-r)*math.factorial(r))
    return combinations

count_combinations(len(nums),2)

404550.0

### Step-by-Step Solution

#### Step 0: Set up
Import necessary packages

In [4]:
import numpy as np

#### Step 1: Get all of the 3 digit numbers

In [5]:
nums = np.arange(100,1000)
nums[:10] # check out the first 10 elements of nums

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [6]:
nums[-10:] # check out the last 10 elements of nums

array([990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

#### Step 2: Calculate the product of every possible pair of 3-digit numbers

In [7]:
# Set up an empty list to collect all of the products of our 3-digit numbers
products = []

# Loop through all of the elements in nums, twice
# This allows us to compare every pair of nums
for num in nums:
    for num2 in nums:
        products.append(num * num2)

products[:10]

[10000, 10100, 10200, 10300, 10400, 10500, 10600, 10700, 10800, 10900]

#### Step 3: Find all palindromes in our list of products

In [8]:
# Set up an empty list to collect all of the palindromes in our products list
palindromes = []

# Loop through every element in products
for product in products:
    if str(product) == str(product)[::-1]: # compare each string to the same string, reversed
        palindromes.append(product)
        
palindromes[:10]

[10201, 11211, 12221, 13231, 14241, 15251, 16261, 17271, 18281, 19291]

#### Step 4: Find the largest palindrome

In [9]:
max(palindromes) 

906609

### Complete Solution

In [10]:
import numpy as np

nums = np.arange(100,1000)

products = []

for num in nums: # loop through every num
    for num2 in nums: # loop through every num again
        products.append(num * num2)

palindromes = []

for product in products:
    if str(product) == str(product)[::-1]: # compare each string to the same string, reversed
        palindromes.append(product)

max(palindromes)

906609


## Challenge 2: Summation of Primes
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below 2,000. Afterward, write a brief explanation walking through your code's logic in markdown.

### Step-by-Step Solution

#### Step 1: Get all of the numbers below 2000

In [11]:
nums = np.arange(2,2000)

#### Step 2: Loop through the nums and divide by known primes
To determine if a number is a prime: Divide it by every prime < the number. If it is divisble by any it's not a prime. If it's not divisible it's a prime.

In [12]:
primes = [] # a place to store primes as we find them

for num in nums:
    remainders = [num % prime == 0 for prime in primes] # remainders is a bool array, True = divisible
    
    if any(remainders) == False: # any() will only return False if all entries are False
            primes.append(num)

#### Step 3: Find the sum of all primes below 200

In [13]:
sum(primes)

277050

### Complete Solution

In [14]:
def sum_primes_below(below):
    nums = np.arange(2,below)
    primes = [] # a place to store primes as we find them

    for num in nums:
        remainders = [num % prime == 0 for prime in primes] 

        if any(remainders) == False:
            primes.append(num)
    
    return(sum(primes))

sum_primes_below(2000) 

277050

## Challenge 3: Multiples of 3 and 5
If we list all of the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6, and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 and 5 below 1,000. Afterward, write a brief explanation walking through your code's logic in markdown.

### Step-by-Step Solution

#### Step 1: Get all of the numbers below 1000

In [15]:
nums = np.arange(2,1000)
nums[:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Step 2: Loop through every number and check if it's divisible by 3 or 5

In [16]:
multiples = []

for num in nums: # for every num
    if num % 3 == 0: # check if it's evenly divisible by 3
        multiples.append(num)
    elif num % 5 == 0: # check if it's evenly divisible by 5
        multiples.append(num)

#### Step 3: Find the sum

In [17]:
sum(multiples)

233168

### Complete Solution

In [18]:
nums = np.arange(2,1000)
nums[:10]

multiples = []

for num in nums:
    if num % 3 == 0:
        multiples.append(num)
    elif num % 5 == 0:
        multiples.append(num)
        
sum(multiples)

233168

## Challenge 4: String Compressor
Implement a method to perform basic string compression using the counts of repeated characters. (This is called run-length encoding.) For example, the string "aabcccccaaa" would become a2b1c5a3. If the “compressed” string would not become smaller than the original string, your method should return the original string. You can assume the string has only uppercase and lowercase letters (a–z). Specify whether your solution is case sensitive or case insensitive and what you would need to change to make it the other. Afterward, write a brief explanation walking through your code's logic in markdown.

### Step-by-Step Solution
Adapted from this reference: https://stackoverflow.com/questions/34443946/count-consecutive-characters

#### Step 1: Initialize several placeholders

In [19]:
string = 'aabcccccaaa'
count = 0
char_counts = []
encoded_string = ''
result = ''

#### Step 2: Loop through each character in the string and compare to previous character

In [20]:
for char in np.arange(len(string)):
        if string[char-1] == string[char]: # compare each char to char-1 (the preceeding character)
            count += 1 # if these are the same, increment count

        else:
            char_counts.append([string[char-1],count]) # when they are different, append the preceeding char and count
            count = 1

char_counts.append([string[char],count])

#### Step 3: Create the encoded version of the string

In [21]:
for pair in char_counts:
        if str(pair[1]) != '0': # handle the cases related to string[-1] appended to start of list
               encoded_string = encoded_string + str(pair[0])+str(pair[1])

#### Step 4: Find the more compressed version of the string (encoded vs original)

In [24]:
if len(encoded_string) < len(string): # the encoded string must be shorter than the original to be 'compressed'
        result = encoded_string
else:
    result = string

print(result)

a2b1c5a3


### Complete Solution
This version is case sensitive. For case insensitive, convert string to lower before first loop: string = string.lower()

In [25]:
def encode_string(string):
    count = 0
    char_counts = []
    encoded_string = ''
    result = ''

    for char in np.arange(len(string)):
        if string[char-1] == string[char]:
            count += 1

        else:
            char_counts.append([string[char-1],count])
            count = 1

    char_counts.append([string[char],count])

    for pair in char_counts:
        if str(pair[1]) != '0': # handle the cases related to string[-1] appended to start of list
               encoded_string = encoded_string + str(pair[0])+str(pair[1])

    if len(encoded_string) < len(string):
        result = encoded_string
    else:
        result = string

    return result

#### Sample outputs 

In [26]:
encode_string('aabcccccaaa')

'a2b1c5a3'

In [27]:
encode_string('aaabbddlllaaabb')

'a3b2d2l3a3b2'

In [28]:
encode_string('jgksjduuuhhsjkalll')
# encoded version: 'j1g1k1s1j1d1u3h2s1j1k1a1l3'

'jgksjduuuhhsjkalll'

In [29]:
encode_string('aabbsssssdd')

'a2b2s5d2'

In [30]:
encode_string('BaBBBBBaa')

'B1a1B5a2'

In [31]:
encode_string('AaabbBdlllaaabb')
# encoded version: 'A1a2b2B1d1l3a3b2'

'AaabbBdlllaaabb'

## *BONUS* Challenge: FizzBuzz
Write a program that prints all of the numbers from 1 to 100. For multiples of 3, instead of the number, print "Fizz;" for multiples of 5, print "Buzz." For numbers that are multiples of both 3 and 5, print "FizzBuzz." Afterward, write a brief explanation walking through your code's logic in markdown.

### Complete Solution

In [33]:
for num in np.arange(1,101): # for every number 1, 100
    if (num % 3 == 0) & (num % 5 == 0): # check for both conditions: divisible by 3 and 5
        print('FizzBuzz')
    elif num % 3 == 0: # check for multiples of 3
        print('Fizz')
    elif num % 5 == 0: # check for multiples of 5
        print('Buzz')
    else: 
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz
